spring.application.name=surfboard-rental-service
#MYSQL CONNECTION
server.port=4040
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.profiles.active=local
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



#aws.s3.secret.key=
#aws.s3.access.key=

